apiVersion: v1
kind: Secret
metadata:
  name: playwright-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  test-user: {{ .Values.secret.testUser }}
  test-password: {{ .Values.secret.testPassword }}